//
// Created by plays on 12/9/2020.
//

#ifndef DESKTOPINTERFACE_APPLICATION_CONSTANTS_H
#define DESKTOPINTERFACE_APPLICATION_CONSTANTS_H

#define APP_WIDTH 900
#define APP_HEIGHT 720
#define WINDOW_TITLE "Physician's Desktop Interface"

#endif //DESKTOPINTERFACE_APPLICATION_CONSTANTS_H
